services:
  postgres_db:
    image: postgres:16-alpine
    container_name: jtk_portfolio_db
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: portfolio_blockchain_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U portfolio_user -d portfolio_blockchain_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      args:
        - VITE_GOOGLE_CLIENT_ID
        - VITE_API_URL
    container_name: jtk_portfolio_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - AWS_REGION=ap-southeast-1
      - DATABASE_URL=postgresql://portfolio_user:secretpassword@postgres_db:5432/portfolio_blockchain_db
      - MULTICHAIN_RPC_URL=http://multichain_node:4242
      - AWS_S3_BUCKET=kota101-ta
      - JWT_SECRET=your-super-secret-key-change-this-in-production
      - ADMIN_EMAIL=admin@university.ac.id
      - ADMIN_PASSWORD=AdminPassword123
      - ADMIN_NAME=Administrator
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CHAIN_NAME=${CHAIN_NAME}
      - AUDIT_STREAM_NAME=${AUDIT_STREAM_NAME}
      - D3_IP=${D3_IP}
      - D3_RPC_PORT=${D3_RPC_PORT}
      - D3_RPC_USERNAME=${D3_RPC_USERNAME}
      - D3_RPC_PASSWORD=${D3_RPC_PASSWORD}
      - D4_IP=${D4_IP}
      - D4_RPC_PORT=${D4_RPC_PORT}
      - D4_RPC_USERNAME=${D4_RPC_USERNAME}
      - D4_RPC_PASSWORD=${D4_RPC_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  pgdata:
