export const text = {
  app: {
    name: "Sistem Portofolio Dosen",
    shortName: "Portofolio",
  },
  nav: {
    beranda: "Beranda",
    dashboard: "Dashboard",
    manajemenAkun: "Manajemen Akun",
    akademik: "Akademik",
    jurusan: "Jurusan",
    programStudi: "Program Studi",
    jabatan: "Jabatan",
    ketuaJurusan: "Ketua Jurusan",
    ketuaProdi: "Ketua Prodi",
    distribusiDokumen: "Distribusi Dokumen",
    kegiatanTridharma: "Kegiatan Tridharma",
    dokumenSaya: "Dokumen Saya",
    monitoringJurusan: "Monitoring Jurusan",
    monitoringProdi: "Monitoring Prodi",
    kegiatan: "Kegiatan",
    laporanRekapitulasi: "Laporan Rekapitulasi",
  },
  greeting: {
    pagi: "Selamat Pagi",
    siang: "Selamat Siang",
    sore: "Selamat Sore",
    malam: "Selamat Malam",
  },
  action: {
    tambah: "Tambah",
    edit: "Edit",
    hapus: "Hapus",
    simpan: "Simpan",
    batal: "Batal",
    cari: "Cari",
    filter: "Filter",
    reset: "Reset",
    export: "Ekspor",
    unduh: "Unduh",
    lihat: "Lihat",
    tutup: "Tutup",
    kirim: "Kirim",
    konfirmasi: "Konfirmasi",
    yaHapus: "Ya, Hapus",
    kembali: "Kembali",
    lanjutkan: "Lanjutkan",
    muatUlang: "Muat Ulang",
  },
  status: {
    aktif: "Aktif",
    tidakAktif: "Tidak Aktif",
    menunggu: "Menunggu",
    disetujui: "Disetujui",
    ditolak: "Ditolak",
    terdistribusi: "Terdistribusi",
    draft: "Draft",
    lengkap: "Lengkap",
    tidakLengkap: "Tidak Lengkap",
  },
  empty: {
    title: "Belum Ada Data",
    description: "Belum ada data untuk ditampilkan.",
    kegiatan: "Belum ada kegiatan. Yuk buat kegiatan pertama!",
    dokumen: "Belum ada dokumen. Unggah dokumen pertama Anda!",
    user: "Belum ada pengguna.",
    hasil: "Tidak ada hasil yang cocok dengan pencarian Anda.",
  },
  error: {
    umum: "Terjadi kesalahan. Silakan coba lagi.",
    muat: "Gagal memuat data.",
    simpan: "Gagal menyimpan data.",
    hapus: "Gagal menghapus data.",
    jaringan: "Tidak ada koneksi internet.",
  },
  auth: {
    email: "Email",
    password: "Kata Sandi",
    login: "Masuk",
    loginGoogle: "Masuk dengan Google",
    logout: "Keluar",
    belumPunyaAkun: "Belum punya akun?",
    lupaPassword: "Lupa kata sandi?",
  },
  kegiatan: {
    title: "Kegiatan",
    semua: "Semua",
    pendidikan: "Pendidikan",
    penelitian: "Penelitian",
    pengabdian: "Pengabdian",
    tugasTambahan: "Tugas Tambahan",
    nama: "Nama Kegiatan",
    jenis: "Jenis Tridharma",
    kategori: "Kategori",
    tanggalMulai: "Tanggal Mulai",
    tanggalSelesai: "Tanggal Selesai",
    tahunAkademik: "Tahun Akademik",
    semester: "Semester",
    peran: "Peran",
    pencatat: "Pencatat",
    anggota: "Anggota",
    bukti: "Bukti Kegiatan",
    bersama: "Bersama",
    masingMasing: "Masing-masing",
    tambahKegiatan: "Tambah Kegiatan",
    editKegiatan: "Edit Kegiatan",
    detailKegiatan: "Detail Kegiatan",
  },
  dokumen: {
    title: "Dokumen",
    nama: "Nama Dokumen",
    jenis: "Jenis Dokumen",
    tanggal: "Tanggal",
    ukuran: "Ukuran",
    asal: "Asal",
    dariTataUsaha: "Dari Tata Usaha",
    unggahanSendiri: "Unggahan Sendiri",
    uploadDokumen: "Unggah Dokumen",
    preview: "Pratinjau",
    unduhDokumen: "Unduh Dokumen",
    bagikan: "Bagikan",
    verifikasi: "Verifikasi Blockchain",
  },
  distribusi: {
    title: "Distribusi Dokumen",
    totalDokumen: "Total Dokumen",
    sudahTerdistribusi: "Sudah Terdistribusi",
    belumTerdistribusi: "Belum Terdistribusi",
    jenisDokumen: "Jenis Dokumen",
    distribusikan: "Distribusikan",
    penerima: "Penerima",
    pilihPenerima: "Pilih Penerima",
    kirimUlang: "Kirim Ulang",
    hapusPenerima: "Hapus Penerima",
  },
  monitoring: {
    title: "Monitoring",
    kelengkapan: "Kelengkapan",
    prodi: "Program Studi",
    dosen: "Dosen",
    total: "Total",
    rekap: "Rekapitulasi",
    buatRekap: "Buat Rekapitulasi",
    editRekap: "Edit Rekapitulasi",
  },
  user: {
    title: "Pengguna",
    nama: "Nama",
    nip: "NIP",
    nidn: "NIDN",
    email: "Email",
    peran: "Peran",
    status: "Status",
    terakhirLogin: "Terakhir Login",
    tambahUser: "Tambah Pengguna",
    editUser: "Edit Pengguna",
  },
};

export function getGreeting(): string {
  const hour = new Date().getHours();
  if (hour < 12) return text.greeting.pagi;
  if (hour < 15) return text.greeting.siang;
  if (hour < 18) return text.greeting.sore;
  return text.greeting.malam;
}
